name: Lint
on: [pull_request]

jobs:
  checkov:
    name: terraform
    runs-on: ubuntu-latest
    steps:
    -
        uses: actions/checkout@v2
    -
        name: Set up Python
        uses: actions/setup-python@v2
    -
        name: Test with Checkov
        run: |
          pip install checkov
          checkov -d terraform/
