name: lint
on: [pull_request]

env:
  TF_LOG: WARN

jobs:

  tflint:

    name: terraform
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      pull-requests: write

    steps: 
    -
      uses: actions/checkout@v3
    -
      uses: hashicorp/setup-terraform@v1
    -
      name: Terraform fmt
      run: terraform fmt -check -recursive
    -
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.8.0
      with:
        token_format: access_token
        access_token_lifetime: 900s
        workload_identity_provider: projects/1049058775616/locations/global/workloadIdentityPools/main-pool/providers/github
        service_account: terraform-ci-cd@ironsecurity.iam.gserviceaccount.com
        create_credentials_file: true
        activate_credentials_file: true
    -
      name: Terraform Init
      run: terraform init
    -
      name: Terraform lint
      uses: reviewdog/action-tflint@v1.17
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review
        fail_on_error: true
    -
      name: Cleanup
      if: always()
      run: rm "${GOOGLE_APPLICATION_CREDENTIALS}" || true
