name: scan
on: [pull_request]

jobs:
  checkov:
    name: terraform
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v2
    -
      name: Set up Python
      uses: actions/setup-python@v2
    -
      name: Test with Checkov
      uses: bridgecrewio/checkov-action@v12.641.0
      with:
        framework: terraform 
        quiet: true
