name: scan
on: [pull_request]

jobs:

  checkov:

    name: checkov
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    -
      uses: actions/checkout@v2
    -
      name: Set up Python
      uses: actions/setup-python@v2
    -
      name: Test with Checkov
      uses: bridgecrewio/checkov-action@master
      with:
        quiet: true
  
  trivy:

    name: trivy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      

    steps:
    -
      uses: actions/checkout@v2
    -
      name: Run Trivy vulnerability scanner in IaC mode
      uses: aquasecurity/trivy-action@0.1.0
      with:
        scan-type: 'config'
        hide-progress: false
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH,MEDIUM'
    -
      name: Upload Trivy scan results to GitHub Security tab
      if: always()
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: 'trivy-results.sarif'
