name: scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: '23 17 * * 3'

jobs:

  checkov:

    name: checkov
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
    -
      uses: actions/checkout@v2
    -
      name: Set up Python
      uses: actions/setup-python@v2
    -
      name: Test with Checkov
      uses: bridgecrewio/checkov-action@master
      with:
        quiet: true
  
  trivy:

    name: trivy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
    -
      uses: actions/checkout@v2
    -
      name: Run Trivy vulnerability scanner in IaC mode
      uses: aquasecurity/trivy-action@0.3.0
      with:
        hide-progress: false
        exit-code: '1'
        ignore-unfixed: true
        scan-type: 'config'
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH,MEDIUM'
    -
      name: Upload Trivy scan results to GitHub Security tab
      if: always()
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: 'trivy-results.sarif'
