name: test
on: [pull_request]

env:
  TF_LOG: DEBUG
  TF_VAR_cf_email: ${{ secrets.TF_VAR_CF_EMAIL }}
  TF_VAR_cf_api_key: ${{ secrets.TF_VAR_CF_API_KEY }}
  TF_VAR_github_token: ${{ secrets.TF_VAR_GITHUB_TOKEN }}
  GCLOUD_PROJECT: ironsecurity

jobs:
  test:
    permissions:
      contents: read
      id-token: 'write'
    name: terraform
    runs-on: ubuntu-latest
    steps: 
    -
      uses: actions/checkout@v2
    -
      uses: hashicorp/setup-terraform@v1
    -
      name: Terraform fmt
      run: terraform fmt -check=true
    -
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.3.0
      id: gcloud_auth
      with:
        token_format: access_token
        access_token_lifetime: 900s
        workload_identity_provider: projects/ironsecurity/locations/global/workloadIdentityPools/main-pool/providers/github
        service_account: terraform-ci-cd@ironsecurity.iam.gserviceaccount.com
        create_credentials_file: true
        activate_credentials_file: false
    -
      uses: 'google-github-actions/setup-gcloud@v0.2.1'
      with:
        project_id: ${{ env.GCLOUD_PROJECT }}
    -
      name: 'gcloud login'
      run: |-
        gcloud auth login --brief --cred-file="${{ steps.gcloud_auth.outputs.credentials_file_path }}"
    -
      name: Terraform Init
      run: terraform init
      env:
        GCP_TOKEN: ${{ steps.gcloud_auth.outputs.access_token }}
    -
      name: Terraform Validate
      run: terraform validate -no-color
    -
      name: Terraform Plan
      run: terraform plan -no-color -lock=false -input=false
    -
      name: Cleanup
      if: always()
      run: rm "${GOOGLE_APPLICATION_CREDENTIALS}" || true
