name: test

on:
  pull_request:
    paths-ignore:
    - helm/
    - kubernetes/

env:
  TF_LOG: INFO
  TF_VAR_cf_email: ${{ secrets.TF_VAR_CF_EMAIL }}
  TF_VAR_cf_api_key: ${{ secrets.TF_VAR_CF_API_KEY }}
  TF_VAR_github_token: ${{ secrets.TF_VAR_GITHUB_TOKEN }}

jobs:

  test-infra:

    name: terraform infrastructure
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps: 
    -
      uses: actions/checkout@v3
    -
      uses: hashicorp/setup-terraform@v2
    -
      name: Terraform fmt
      run: terraform fmt -check=true
    -
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1.0.0
      with:
        access_token_lifetime: 900s
        workload_identity_provider: projects/1049058775616/locations/global/workloadIdentityPools/main-pool/providers/github-sa-provider
        service_account: terraform-ci-cd@ironsecurity.iam.gserviceaccount.com
        create_credentials_file: true
    -
      name: Terraform Init
      run: terraform init
    -
      name: Terraform Validate
      run: terraform validate -no-color
    -
      name: Terraform Plan
      run: terraform plan -no-color -lock=false -input=false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Cleanup
      if: always()
      run: rm "${GOOGLE_APPLICATION_CREDENTIALS}" || true
