name: Test
on: [pull_request]

env:
  TF_LOG: WARN

jobs:
  testterraform:
    name: terraform
    runs-on: ubuntu-latest
    steps: 
    -
      uses: actions/checkout@v2
    -
      name: Terraform - Init
      uses: hashicorp/terraform-github-actions@v0.8.0
      with:
        tf_actions_subcommand: "init"
        tf_actions_version: "latest"
        tf_actions_working_dir: terraform/
    -
      name: Terraform - Lint
      uses: reviewdog/action-tflint@v1.13
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
        flags: "--deep"
        tf_actions_working_dir: terraform/
    -
      name: Terraform - Validate
      uses: hashicorp/terraform-github-actions@v0.8.0
      with:
        tf_actions_subcommand: "validate"
        tf_actions_version: "latest"
        tf_actions_working_dir: terraform/
    -
      name: Terraform - Plan
      uses: hashicorp/terraform-github-actions@v0.8.0
      with:
        tf_actions_subcommand: "plan"
        tf_actions_version: "latest"
        tf_actions_working_dir: terraform/
      env:
        TF_VAR_project_id: ${{ secrets.project_id }}
